blueye_position: "0.0 0.0 1.0"
blueye_orientation: "0.0 0.0 0.0"
pipeline_position: "1.85 0.0 3.5"
pipeline_orientation: "0.0 0.0 0.0"
docking_rig_position: "10.0 -25.0 3.95"
docking_rig_orientation: "0.0 0.0 3.14"
