drone_position: "0.0 7.5 0.0"
drone_orientation: "-1.57 0.0 0.0"
water_jerlow: "0.20"
docking_station_position: "0.0 7.5 4.0"
docking_station_orientation: "1.57 0.0 1.57"
docking_rig_position: "0.0 5.0 4.4"
docking_rig_orientation: "0.0 0.0 0.0"
blueye_position: "1.57 3.39 2.60"
blueye_orientation: "0.0 0.0 0.0"
pool_position: "0.0 3.0 -0.2"
pool_orientation: "-1.57 0.0 0.0"